/* This file was generated by lv6 version v6.106.1. */
/*  lv6 script.lus -node Main -2c -cc */
/* on linux the 19/01/2023 at 01:23:55 */

#ifndef _SOC2C_PREDEF_TYPES
#define _SOC2C_PREDEF_TYPES
typedef int _boolean;
typedef int _integer;
typedef char* _string;
typedef double _real;
typedef double _double;
typedef float _float;
#define _false 0
#define _true 1
#endif
// end of _SOC2C_PREDEF_TYPES